=== BackupTheBerlios/cbear-svn/trunk/cbear.sourceforge.net/api/main.xsd
<?xml version="1.0"?>
<schema 
	xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://cbear.sourceforge.net/api"
	xmlns:api="http://cbear.sourceforge.net/api"
	elementFormDefault="qualified">

	<element name="library">	
		<complexType>
			<complexContent>
				<extension base="api:definition">
					<sequence>
						<element ref="api:using" minOccurs="0" maxOccurs="unbounded"/>
						<choice maxOccurs="unbounded">
							<element ref="api:interface"/>
							<element ref="api:struct"/>
							<element ref="api:type"/>
							<element ref="api:enum"/>
							<element ref="api:object"/>
						</choice>
					</sequence>
					<attribute name="version" use="optional" type="api:version"/>
				</extension>
			</complexContent>
		</complexType>	
	</element>

	<element name="using">
		<complexType>
			<complexContent>
				<extension base="api:definition">
					<attribute name="id" type="api:id"/>
					<attribute name="href" type="api:href"/>
				</extension>
			</complexContent>
		</complexType>
	</element>

	<element name="interface">
		<complexType>
			<complexContent>
				<extension base="api:definition">
					<sequence>
						<element ref="api:type.ref" minOccurs="0" maxOccurs="unbounded"/>
						<choice minOccurs="0" maxOccurs="unbounded">
							<element ref="api:property"/>
							<element ref="api:method"/>
						</choice>
					</sequence>
				</extension>
			</complexContent>
		</complexType>
	</element>

	<element name="property">
		<complexType>
			<complexContent>
				<extension base="api:definition">
					<sequence>
						<element ref="api:get" minOccurs="0"/>
						<element ref="api:set" minOccurs="0"/>
						<element ref="api:type.ref"/>
						<element ref="api:parameter" minOccurs="0" maxOccurs="unbounded"/>
					</sequence>
				</extension>
			</complexContent>
		</complexType>
	</element>

	<element name="get"/>
	<element name="set"/>

	<element name="method">
		<complexType>
			<complexContent>
				<extension base="api:definition">
					<sequence>
						<element ref="api:type.ref" minOccurs="0"/>
						<element ref="api:parameter" minOccurs="0" maxOccurs="unbounded"/>
					</sequence>
				</extension>
			</complexContent>
		</complexType>
	</element>

	<element name="parameter">
		<complexType>
			<sequence>
				<element ref="api:in" minOccurs="0"/>
				<element ref="api:out" minOccurs="0"/>
				<element ref="api:type.ref"/>
			</sequence>
		</complexType>
	</element>

	<element name="in"/>
	<element name="out"/>

	<element name="struct">
		<complexType>
			<complexContent>
				<extension base="api:definition">
					<sequence>
						<element ref="api:object" minOccurs="0" maxOccurs="unbounded"/>
					</sequence>
				</extension>			
			</complexContent>
		</complexType>
	</element>

	<element name="enum">
		<complexType>
			<complexContent>
				<extension base="api:definition">
					<sequence>
						<element ref="api:item" minOccurs="0" maxOccurs="unbounded"/>
					</sequence>
				</extension>
			</complexContent>		
		</complexType>
	</element>

	<element name="item">
		<complexType>
			<complexContent>
				<extension base="api:definition">
					<sequence>
						<element ref="api:const"/>
					</sequence>
				</extension>
			</complexContent>		
		</complexType>
	</element>

	<element name="type">
		<complexType>
			<complexContent>
				<extension base="api:definition">
					<choice minOccurs="0" maxOccurs="unbounded">
						<element ref="api:type.parameter"/>
					</choice>
				</extension>
			</complexContent>
		</complexType>
	</element>

	<element name="type.parameter">
		<complexType>
			<attribute name="id" type="api:id"/>
		</complexType>
	</element>

	<element name="object">
		<complexType>
			<complexContent>
				<extension base="api:definition">
					<sequence>
						<element ref="api:type.ref"/>
					</sequence>
				</extension>
			</complexContent>
		</complexType>
	</element>

	<element name="type.ref">
		<complexType>
			<choice minOccurs="0" maxOccurs="unbounded">
				<element ref="api:type.ref"/>
				<element ref="api:const"/>
			</choice>
			<attribute name="id" type="api:id"/>
			<attribute name="library" type="api:library"/>
		</complexType>
	</element>

	<element name="const">
		<complexType>
			<attribute name="value" type="api:value"/>
		</complexType>
	</element>

	<simpleType name="id">
		<restriction base="token"/>
	</simpleType>

	<simpleType name="library">
		<restriction base="token"/>
	</simpleType>

	<simpleType name="uuid">
		<restriction base="token"/>
	</simpleType>

	<simpleType name="version">
		<restriction base="token"/>
	</simpleType>

	<simpleType name="libray">
		<restriction base="token"/>
	</simpleType>

	<simpleType name="brief">
		<restriction base="string"/>
	</simpleType>

	<simpleType name="value">
		<restriction base="token"/>
	</simpleType>

	<simpleType name="href">
		<restriction base="token"/>
	</simpleType>

	<complexType name="definition">
		<sequence>
			<element ref="api:comment" minOccurs="0"/>
			<element ref="api:pragma" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="id" type="api:id"/>
		<attribute name="uuid" use="optional" type="api:id"/>
		<attribute name="brief" use="optional" type="api:brief"/>
	</complexType>

	<element name="pragma">
		<complexType mixed="true">
			<choice minOccurs="0" maxOccurs="unbounded">
				<any processContents="skip"/>
			</choice>
		</complexType>
	</element>

	<element name="comment">
		<complexType mixed="true">
			<choice minOccurs="0" maxOccurs="unbounded">
				<any processContents="skip"/>
			</choice>
		</complexType>
	</element>

</schema>

=== BackupTheBerlios/cbear-svn/v0.4.0/cbear.berlios.de/api/example.xml
<?xml version="1.0"?>
<!--
The MIT License

Copyright (c) 2005 C Bear (http://cbear.berlios.de)

Permission is hereby granted, free of charge, to any person obtaining a copy of 
this software and associated documentation files (the "Software"), to deal in 
the Software without restriction, including without limitation the rights to 
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so, 
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all 
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR 
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER 
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-->
<?xml-stylesheet type="text/xsl" href="html.xsl"?>
<library 
	xmlns="http://cbear.berlios.de/api"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://cbear.berlios.de/api main.xsd"
	xmlns:html="http://www.w3.org/1999/xhtml"
	id="cbear.berlios.de/api/example"
	brief="C Bear, API Example"
	uuid="C06BCE4E-E1D6-4c62-9A4F-D593091816A6">

<comment>
	<public>
		Example:
		<html:ul>
			<html:li>A</html:li>
			<html:li>B</html:li>
		</html:ul>
	</public>
	<private>
		Example:
		<html:ul>
			<html:li>A</html:li>
			<html:li>B</html:li>
		</html:ul>
	</private>
</comment>

<using id="Base" href="base.xml"/>

<interface id="ITime">
	<property id="Date">
		<get/>
		<type.ref library="Base" id="date"/>
	</property>
	<property id="Clock">
		<get/>
		<type.ref library="Base" id="uint">
			<const value="32"/>
		</type.ref>
	</property>
</interface>

<interface id="IDeviceInfo">
	<property id="Name">
		<get/>
		<type.ref library="Base" id="string"/>
	</property>
</interface>

<interface id="IModuleInfo">
	<type.ref id="IDeviceInfo"/>
</interface>

<interface id="IModuleInfoList">
	<property id="Count">
		<get/>
		<type.ref library="Base" id="int32"/>
	</property>
	<property id="Item">
		<get/>
		<type.ref id="IModuleInfo"/>
		<parameter>
			<in/>
			<type.ref library="Base" id="int32"/>
		</parameter>
	</property>
	<method id="Update"/>
</interface>

<interface id="IMain">
	<method id="Create">
		<type.ref id="IModuleInfo"/>
		<parameter>
			<in/>
			<type.ref library="Base" id="string"/>
		</parameter>
	</method>
	<method id="Reserved">
		<type.ref library="Base" id="vector">
			<type.ref library="Base" id="uint8"/>
		</type.ref>
		<parameter>
			<in/>
			<type.ref library="Base" id="vector">
				<type.ref library="Base" id="uint8"/>
			</type.ref>
		</parameter>
	</method>
	<property id="A">
		<get/>
		<type.ref id="IModuleInfoList"/>
	</property>
</interface>

<interface id="IA"/>
<interface id="IB"/>
<interface id="IC">
	<type.ref id="IA"/>
	<type.ref id="IB"/>
</interface>

<enum id="Mode">
	<item id="Disabled"><const value="0"/></item>
	<item id="Enabled"><const value="1"/></item>
</enum>

<struct id="Data">
	<object id="Number">
		<type.ref library="Base" id="int32"/>
	</object>
	<object id="Array">
		<type.ref library="Base" id="fixed.array">
			<type.ref library="Base" id="uint8"/>
			<const value="4"/>
		</type.ref>
	</object>
</struct>

<object id="Main">
	<type.ref id="IMain"/>
</object>

</library>

=== BackupTheBerlios/cbear-svn/trunk/cbear.berlios.de/cms/api.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../api/html.xsl"?>
<library 
	xmlns="http://cbear.berlios.de/api"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://cbear.berlios.de/api ../api/main.xsd"
	xmlns:html="http://www.w3.org/1999/xhtml"
	id="net.sourceforge.cbear.project">

<using id="Base" href="../api/base.xml"/>

<union id="Context">
	<object id="para">
		<type.ref library="Base" id="string"/>
	</object>
</union>

<struct id="Project">

	<type.ref library="Base" id="vector">
		<type.ref id="Project"/>
	</type.ref>

	<type.ref library="Base" id="vector">
		<type.ref id="Context"/>
	</type.ref>

	<object id="name">
		<pragma><xsd:attribute/></pragma>
		<type.ref library="Base" id="string"/>
	</object>

	<object id="id">
		<pragma><xsd:attribute/></pragma>
		<type.ref library="Base" id="optional">
			<type.ref library="Base" id="string"/>
		</type.ref>
	</object>

</struct>

</library>
