=== BackupTheBerlios/cbear-svn/trunk/cbear.berlios.de/cpp/main.xsd
<?xml version="1.0"?>
<schema 
	xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://cbear.berlios.de/cpp"
	xmlns:cpp="http://cbear.berlios.de/cpp"
	elementFormDefault="qualified"
	attributeFormDefault="unqualified">

	<!-- 
		A unit contains a header file (.hpp) and a code file (.cpp).	
		A unit has a name.
	-->
	<element name="unit">
		<complexType>
			<sequence>
				<element ref="cpp:header"/>
				<element ref="cpp:code" minOccurs="0"/>
			</sequence>
			<attribute name="id" type="cpp:id"/>
		</complexType>
	</element>

	<element name="header" type="cpp:content"/>
	<element name="code" type="cpp:content"/>

	<!-- A content contains namespaces, templates and classes. -->
	<complexType name="content">
		<sequence>
			<element ref="cpp:include" minOccurs="0" maxOccurs="unbounded"/>
			<choice minOccurs="0" maxOccurs="unbounded">
				<element ref="cpp:namespace"/>
				<element ref="cpp:class"/>
				<element ref="cpp:template"/>
				<element ref="cpp:typedef"/>
				<element ref="cpp:enum"/>
			</choice>
		</sequence>
	</complexType>

	<!-- An include. -->
	<element name="include">
		<complexType>
			<attribute name="href" type="cpp:href"/>
		</complexType>
	</element>

	<!-- href. -->
	<simpleType name="href">
		<restriction base="string"/>
	</simpleType>

	<!-- 
		A namespace contains everything a content has. 
		A namespace has a name.

			namespace Example
			{
				...
			}
	-->
	<element name="namespace">
		<complexType>
			<choice minOccurs="0" maxOccurs="unbounded">
				<element ref="cpp:namespace"/>
				<element ref="cpp:class"/>
				<element ref="cpp:template"/>
				<element ref="cpp:typedef"/>
				<element ref="cpp:enum"/>
			</choice>
			<attribute name="id" type="cpp:id"/>
		</complexType>
	</element>

	<!--
		A template contains parameters and a class.

			template<class Id1, class Id2>
			class Id
			{
				...
			};
	-->
	<element name="template">
		<complexType>
			<sequence>
				<element ref="cpp:id" minOccurs="0" maxOccurs="unbounded"/>
				<choice>
					<element ref="cpp:class"/>
					<element ref="cpp:method"/>
				</choice>
			</sequence>
		</complexType>
	</element>

	<!--
		A class has a type name, references on parent types and methods.
	
			class Name1::Name2<Name3, Name4<Name5::Name6 > >::Name7: public Parent1
			{
				...
			};
	-->
	<element name="class">
		<complexType>
			<sequence>
				<element ref="cpp:id.ref"/>
				<element ref="cpp:access" minOccurs="0" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>

	<!-- An access. public/private/protected. -->
	<element name="access">
		<complexType>
			<choice minOccurs="0" maxOccurs="unbounded">
				<element ref="cpp:id.ref"/>
				<element ref="cpp:method"/>
				<element ref="cpp:class"/>
				<element ref="cpp:template"/>
				<element ref="cpp:typedef"/>
				<element ref="cpp:enum"/>
			</choice>		
			<attribute name="access" type="cpp:access"/>
		</complexType>	
	</element>

	<!-- An access: public, private or protected. -->
	<simpleType name="access">
		<restriction base="string">
			<enumeration value="public"/>
			<enumeration value="private"/>
			<enumeration value="protected"/>
		</restriction>
	</simpleType>

	<!-- A method 

				virtual Name1::Name2 Method(Name1, Name2<Name3>::Name4) const = 0;
	-->
	<element name="method">
		<complexType>
			<sequence>
				<element ref="cpp:explicit" minOccurs="0"/>
				<element ref="cpp:static" minOccurs="0"/>
				<element ref="cpp:virtual" minOccurs="0"/>
				<element ref="cpp:id.ref" minOccurs="0"/>
				<element ref="cpp:stdcall" minOccurs="0"/>
				<element ref="cpp:parameter" minOccurs="0" maxOccurs="unbounded"/>
				<element ref="cpp:const" minOccurs="0"/>
				<element ref="cpp:abstract" minOccurs="0"/>
				<sequence minOccurs="0">
					<element ref="cpp:ctor" minOccurs="0" maxOccurs="unbounded"/>
					<element ref="cpp:body"/>
				</sequence>
			</sequence>
			<attribute name="id" type="cpp:id"/>
		</complexType>
	</element>

	<!-- A virtual option. -->
	<element name="explicit"/>

	<!-- A virtual option. -->
	<element name="static"/>
	
	<!-- A virtual option. -->
	<element name="virtual"/>

	<!-- A stdcall. -->
	<element name="stdcall"/>

	<!-- A virtual option. -->
	<element name="abstract"/>

	<!-- A method parameter -->
	<element name="parameter">
		<complexType>
			<sequence>
				<element ref="cpp:id.ref"/>
			</sequence>
			<attribute name="id" type="cpp:id" use="optional"/>
		</complexType>
	</element>

	<!-- A method body -->
	<element name="body">
		<complexType>
			<choice minOccurs="0" maxOccurs="unbounded">
				<element ref="cpp:id.ref"/>
				<element ref="cpp:try"/>
			</choice>
		</complexType>
	</element>

	<!-- try -->
	<element name="try">
		<complexType>
			<sequence>
				<element ref="cpp:body"/>
				<element ref="cpp:catch" minOccurs="1" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>

	<!-- catch -->
	<element name="catch">
		<complexType>
			<sequence>
				<element ref="cpp:parameter"/>
				<element ref="cpp:body"/>
			</sequence>
		</complexType>
	</element>

	<!-- A ctor -->
	<element name="ctor">
		<complexType>
			<sequence>
				<element ref="cpp:id.ref"/>
			</sequence>
		</complexType>
	</element>

	<!-- 
		A type definition 
		
			typedef ... Name;	
	-->
	<element name="typedef">
		<complexType>
			<sequence>
				<element ref="cpp:id.ref"/>
			</sequence>
			<attribute name="id" type="cpp:id"/>
		</complexType>
	</element>

	<!-- An enumeration -->
	<element name="enum">
		<complexType>
			<sequence>
				<element ref="cpp:item" minOccurs="0" maxOccurs="unbounded"/>
			</sequence>
			<attribute name="id" type="cpp:id" use="required"/>
		</complexType>
	</element>

	<!-- An item -->
	<element name="item">
		<complexType>
			<attribute name="id" type="cpp:id" use="required"/>
			<attribute name="value" type="cpp:value" use="required"/>			
		</complexType>
	</element>

	<!--
		A type name contains a name and optional type parameters.

			Name1<Name2, Name3, Name4>
	-->
	<element name="id.ref">
		<complexType>
			<sequence>
				<element ref="cpp:id.ref" minOccurs="0" maxOccurs="unbounded"/>
			</sequence>
			<attribute name="id" type="cpp:id"/>
			<attribute name="type" type="cpp:type"/>
		</complexType>
	</element>

	<!-- A constant. -->
	<element name="const"/>

	<!-- A value type. -->
	<simpleType name="value">
		<restriction base="string"/>
	</simpleType>

	<!-- A type. -->
	<simpleType name="type">
		<restriction base="string">
			<enumeration value="&lt;&gt;"/>
			<enumeration value="::"/>
			<enumeration value="."/>
			<enumeration value="()"/>
			<enumeration value="[]"/>
			<enumeration value="->"/>
			<enumeration value="&amp;"/>
			<enumeration value="const"/>
			<enumeration value="typename"/>
			<enumeration value="declare"/>
			<enumeration value="return"/>
			<enumeration value="this"/>
			<enumeration value="|"/>
			<enumeration value="="/>
		</restriction>
	</simpleType>

	<!-- An id element. -->
	<element name="id">
		<complexType>
			<attribute name="id" type="cpp:id"/>
		</complexType>
	</element>

	<!-- A id type. -->
	<simpleType name="id">
		<restriction base="token"/>
	</simpleType>

</schema>

=== BackupTheBerlios/cbear-svn/branches/nn/cbear.berlios.de/cpp/examples/comment.cpp.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../html.xsl"?>
<unit
	xmlns="http://cbear.berlios.de/cpp"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://cbear.berlios.de/cpp ../main.xsd"
	xmlns:html="http://www.w3.org/1999/xhtml"
	id="cbear.berlios.de/cpp/examples/typedef">

<header>

<namespace id="cbear_berlios_de">
<namespace id="cpp">
<namespace id="examples">

  <comment>Some type comment</comment>
	<typedef id="Type1">
		<id.ref id="ClassN"/>
	</typedef>

</namespace>
</namespace>
</namespace>

</header>

</unit>

=== BackupTheBerlios/cbear-svn/v0.4.0/cbear.berlios.de/cpp/examples/class.cpp.xml
<?xml version="1.0"?>
<!--
The MIT License

Copyright (c) 2005 C Bear (http://cbear.berlios.de)

Permission is hereby granted, free of charge, to any person obtaining a copy of 
this software and associated documentation files (the "Software"), to deal in 
the Software without restriction, including without limitation the rights to 
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so, 
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all 
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR 
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER 
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-->
<?xml-stylesheet type="text/xsl" href="../html.xsl"?>
<unit
	xmlns="http://cbear.berlios.de/cpp"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://cbear.berlios.de/cpp ../main.xsd"
	xmlns:html="http://www.w3.org/1999/xhtml"
	id="net/sourceforge/cbear/cpp/examples/class">

<header>

<namespace id="net">
<namespace id="sourceforge">
<namespace id="cbear">
<namespace id="cpp">
<namespace id="examples">

	<class>
		<id.ref type="::">
			<id.ref id="Class1"/>
			<id.ref id="Class2" type="&lt;&gt;">
				<id.ref id="Class3"/>
				<id.ref id="Class4"/>
			</id.ref>
			<id.ref id="Class5"/>
		</id.ref>

		<access access="public">
			<id.ref id="Class6"/>
		</access>

		<access access="private">
			<class>
				<id.ref id="Class10"/>
			</class>
		</access>

	</class>

	<class>
		<id.ref id="Class10"/>

	</class>

	<class>
		<id.ref id="Class11"/>

		<access access="protected">
			<id.ref id="Class16"/>
		</access>

		<access access="private">
			<id.ref id="Class17" type="&lt;&gt;">
				<id.ref type="::">
					<id.ref id="Class23"/>
					<id.ref id="Class24"/>
					<id.ref id="Class25"/>
				</id.ref>
				<id.ref id="Class18" type="&lt;&gt;">
					<id.ref id="Class19"/>
				</id.ref>
			</id.ref>
		</access>

	</class>

</namespace>

	<class>
		<id.ref id="Class10"/>
	</class>

</namespace>
</namespace>
</namespace>
</namespace>

</header>

<code>

<namespace id="net">
<namespace id="sourceforge">
<namespace id="cbear">
<namespace id="cpp">
<namespace id="examples">
</namespace>
</namespace>
</namespace>
</namespace>
</namespace>

</code>

</unit>

=== BackupTheBerlios/cbear-svn/branches/kyr/cbear.berlios.de/cpp/examples/template.cpp.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../html.xsl"?>
<unit
	xmlns="http://cbear.berlios.de/cpp"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://cbear.berlios.de/cpp ../main.xsd"
	xmlns:html="http://www.w3.org/1999/xhtml"
	id="net/sourceforge/cbear/cpp/examples/template">

<header>

<namespace id="net">
<namespace id="sourceforge">
<namespace id="cbear">
<namespace id="cpp">
<namespace id="examples">

	<template>
		<id id="Class3"/>
		<id id="Class6"/>
		<class>

			<id.ref type="::">
				<id.ref id="Class1"/>
				<id.ref id="Class2" type="&lt;&gt;">
					<id.ref id="Class3"/>
					<id.ref id="Class4" type="&lt;&gt;"/>
				</id.ref>
				<id.ref id="Class5"/>
			</id.ref>

			<access access="public">
				<id.ref id="Class6"/>

				<template>
					<id id="Class100"/>
					<class>
						<id.ref id="Class10"/>
					</class>
				</template>

			</access>

		</class>
	</template>

	<template>
		<id id="Class100"/>
		<class>
			<id.ref id="Class10"/>
		</class>
	</template>

	<template>
		<class>
			<id.ref id="Class11"/>

			<access access="private">
				<id.ref id="Class16"/>
			</access>

			<access access="public">
				<id.ref id="Class17" type="&lt;&gt;">
					<id.ref type="::">
						<id.ref id="Class23"/>
						<id.ref id="Class24"/>
						<id.ref id="Class25"/>
					</id.ref>
					<id.ref id="Class18" type="&lt;&gt;">
						<id.ref id="Class19"/>
					</id.ref>
				</id.ref>
			</access>

			<access access="public">
				<class>
					<id.ref id="Class10"/>

				</class>
			</access>

		</class>
	</template>

</namespace>
</namespace>
</namespace>
</namespace>
</namespace>

</header>

<code>

<namespace id="net">
<namespace id="sourceforge">
<namespace id="cbear">
<namespace id="cpp">
<namespace id="examples">
</namespace>
</namespace>
</namespace>
</namespace>
</namespace>

</code>

</unit>

=== BackupTheBerlios/cbear-svn/v0.4.0/cbear.berlios.de/range/traits.xml
<?xml version="1.0"?>
<!--
The MIT License

Copyright (c) 2005 C Bear (http://cbear.berlios.de)

Permission is hereby granted, free of charge, to any person obtaining a copy of 
this software and associated documentation files (the "Software"), to deal in 
the Software without restriction, including without limitation the rights to 
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so, 
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all 
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR 
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER 
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-->
<?xml-stylesheet type="text/xsl" href="../cpp/html.xsl"?>
<unit 
	xmlns="http://cbear.berlios.de/cpp" 
	id="cbear.berlios.de/range/traits"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://cbear.berlios.de/cpp ../cpp/main.xsd">
<header>
<namespace id="cbear_berlios_de">
<namespace id="range">

<template>
	<id id="Container"/>
	<class>
		<id.ref id="traits"/>
		<access access="public">
			<typedef id="container"><id.ref id="Container"/></typedef>
			<typedef id="iterator"><id.ref id="..."/></typedef>
			<typedef id="difference_type"><id.ref id="..."/></typedef>
			<typedef id="size_type"><id.ref id="..."/></typedef>
			<typedef id="referense"><id.ref id="..."/></typedef>
			<typedef id="pointer"><id.ref id="..."/></typedef>
			<typedef id="value_type"><id.ref id="..."/></typedef>
			<typedef id="reverse_iterator"><id.ref id="..."/></typedef>
			<method id="begin">
				<static/>
				<id.ref id="iterator"/>
				<parameter>
					<id.ref type="&amp;"><id.ref id="container"/></id.ref>
				</parameter>
			</method>
			<method id="end">
				<static/>
				<id.ref id="iterator"/>
				<parameter>
					<id.ref type="&amp;"><id.ref id="container"/></id.ref>
				</parameter>
			</method>
			<method id="front">
				<static/>
				<id.ref id="reference"/>
				<parameter>
					<id.ref type="&amp;"><id.ref id="container"/></id.ref>
				</parameter>
			</method>
			<method id="back">
				<static/>
				<id.ref id="reference"/>
				<parameter>
					<id.ref type="&amp;"><id.ref id="container"/></id.ref>
				</parameter>
			</method>
			<method id="at">
				<static/>
				<id.ref id="reference"/>
				<parameter>
					<id.ref type="&amp;"><id.ref id="container"/></id.ref>
				</parameter>
				<parameter>
					<id.ref id="size_type"/>
				</parameter>
			</method>
			<method id="empty">
				<static/>
				<id.ref id="bool"/>
				<parameter>
					<id.ref type="&amp;"><id.ref id="container"/></id.ref>
				</parameter>
			</method>
			<method id="size">
				<static/>
				<id.ref id="size_type"/>
				<parameter>
					<id.ref type="&amp;"><id.ref id="container"/></id.ref>
				</parameter>
			</method>
			<method id="rbegin">
				<static/>
				<id.ref id="reverse_iterator"/>
				<parameter>
					<id.ref type="&amp;"><id.ref id="container"/></id.ref>
				</parameter>
			</method>
			<method id="rend">
				<static/>
				<id.ref id="reverse_iterator"/>
				<parameter>
					<id.ref type="&amp;"><id.ref id="container"/></id.ref>
				</parameter>
			</method>
		</access>
	</class>
</template>

</namespace>
</namespace>
</header>
</unit>

=== BackupTheBerlios/cbear-svn/tags/0.7/cbear.berlios.de/range/pointer.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../cpp/html.xsl"?>
<unit 
	xmlns="http://cbear.berlios.de/cpp" 
	id="cbear.berlios.de/range/pointer"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://cbear.berlios.de/cpp ../cpp/main.xsd">
<header>
<namespace id="cbear_berlios_de">
<namespace id="range">

<template>
	<id id="Container"/>
	<class>
		<id.ref id="pointer"/>
		<access access="public">
			<typedef id="type"><id.ref id="..."/></typedef>
		</access>
	</class>
</template>

</namespace>
</namespace>
</header>
</unit>

=== BackupTheBerlios/cbear-svn/branches/nn/cbear.berlios.de/cpp/examples/namespace.cpp.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../html.xsl"?>
<unit
	xmlns="http://cbear.berlios.de/cpp"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://cbear.berlios.de/cpp ../main.xsd"
	xmlns:html="http://www.w3.org/1999/xhtml"
	id="net/sourceforge/cbear/cpp/examples/namespace">

<header>

<namespace id="net">
<namespace id="sourceforge">
<namespace id="cbear">
<namespace id="cpp">
<namespace id="examples">
</namespace>

</namespace>
</namespace>
</namespace>
</namespace>

</header>

<code>

<namespace id="net">
<namespace id="sourceforge">
<namespace id="cbear">
<namespace id="cpp">
<namespace id="examples">
</namespace>
</namespace>
</namespace>
</namespace>
</namespace>

</code>

</unit>

=== BackupTheBerlios/cbear-svn/trunk/cbear.berlios.de/range/iterator_range.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../cpp/html.xsl"?>
<unit 
	xmlns="http://cbear.berlios.de/cpp" 
	id="cbear.berlios.de/range/iterator_range"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://cbear.berlios.de/cpp ../cpp/main.xsd">
<header>
<namespace id="cbear_berlios_de">
<namespace id="range">
	<template>
		<id id="Iterator"/>
		<class>
			<id.ref id="iterator_range"/>
			<access access="public">
				<id.ref type="::">
					<id.ref id="policy"/>
					<id.ref id="wrap" type="&lt;&gt;">
						<id.ref id="iterator_range" type="&lt;&gt;">
							<id.ref id="Iterator"/>
						</id.ref>
						<id.ref type="::">
							<id.ref/>
							<id.ref id="std"/>
							<id.ref id="pair" type="&lt;&gt;">
								<id.ref id="Iterator"/>
								<id.ref id="Iterator"/>
							</id.ref>
						</id.ref>
					</id.ref>
				</id.ref>
				<id.ref id="helper" type="&lt;&gt;">
					<id.ref id="iterator_range" type="&lt;&gt;">
						<id.ref id="Iterator"/>
					</id.ref>
					<id.ref id="Iterator"/>
					<id.ref id="Iterator"/>
				</id.ref>
				<typedef id="iterator">
					<id.ref id="Iterator"/>
				</typedef>
				<typedef id="const_iterator">
					<id.ref id="Iterator"/>
				</typedef>
				<typedef id="internal_type">
					<id.ref type="::">
						<id.ref/>
						<id.ref id="std"/>
						<id.ref id="pair" type="&lt;&gt;">
							<id.ref id="Iterator"/>
							<id.ref id="Iterator"/>
						</id.ref>
					</id.ref>
				</typedef>
				<method id="iterator_range"/>
				<method id="iterator_range">
					<parameter>
						<id.ref type="&amp;">
							<id.ref type="const"><id.ref id="iterator"/></id.ref>
						</id.ref>
					</parameter>
					<parameter>
						<id.ref type="&amp;">
							<id.ref type="const"><id.ref id="iterator"/></id.ref>
						</id.ref>
					</parameter>
				</method>
				<method id="iterator_range">
					<explicit/>
					<parameter>
						<id.ref type="&amp;">
							<id.ref type="const"><id.ref id="internal_type"/></id.ref>
						</id.ref>
					</parameter>
				</method>
				<template>
					<id id="Range"/>
					<method id="iterator_range">
						<explicit/>
						<parameter>
							<id.ref type="&amp;">
								<id.ref type="const"><id.ref id="Range"/></id.ref>
							</id.ref>
						</parameter>
					</method>
				</template>
				<template>
					<id id="Range"/>
					<method id="iterator_range">
						<explicit/>
						<parameter>
							<id.ref type="&amp;"><id.ref id="Range"/></id.ref>
						</parameter>
					</method>
				</template>
				<method id="begin">
					<id.ref id="iterator"/>
					<const/>
				</method>
				<method id="end">
					<id.ref id="iterator"/>
					<const/>
				</method>
			</access>
		</class>
	</template>
	<template>
		<id id="Iterator"/>
		<method id="make_iterator_range">
			<id.ref id="..."/>
			<parameter>
				<id.ref type="&amp;">
					<id.ref type="const"><id.ref id="Iterator"/></id.ref>
				</id.ref>
			</parameter>
			<parameter>
				<id.ref type="&amp;">
					<id.ref type="const"><id.ref id="Iterator"/></id.ref>
				</id.ref>
			</parameter>
		</method>
	</template>
	<template>
		<id id="Iterator"/>
		<method id="make_iterator_range">
			<id.ref id="..."/>
			<parameter>
				<id.ref type="&amp;">
					<id.ref type="const">
						<id.ref type="::">
							<id.ref/>
							<id.ref id="std"/>
							<id.ref id="pair" type="&lt;&gt;">
								<id.ref id="Iterator"/>
								<id.ref id="Iterator"/>
							</id.ref>
						</id.ref>
					</id.ref>
				</id.ref>
			</parameter>
		</method>
	</template>
	<template>
		<id id="Range"/>
		<method id="make_iterator_range">
			<id.ref id="..."/>
			<parameter>
				<id.ref type="&amp;">
					<id.ref type="const"><id.ref id="Range"/></id.ref>
				</id.ref>
			</parameter>
		</method>
	</template>
	<template>
		<id id="Range"/>
		<method id="make_iterator_range">
			<id.ref id="..."/>
			<parameter>
				<id.ref type="&amp;"><id.ref id="Range"/></id.ref>
			</parameter>
		</method>
	</template>
</namespace>
</namespace>
</header>
</unit>

=== BackupTheBerlios/cbear-svn/branches/trunk/cbear.berlios.de/cpp/examples/typedef.cpp.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="../html.xsl"?>
<unit
	xmlns="http://cbear.berlios.de/cpp"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://cbear.berlios.de/cpp ../main.xsd"
	xmlns:html="http://www.w3.org/1999/xhtml"
	id="cbear.berlios.de/cpp/examples/typedef">

<header>

<namespace id="cbear_berlios_de">
<namespace id="cpp">
<namespace id="examples">

	<typedef id="Type1">
		<id.ref id="ClassN"/>
	</typedef>

	<template>
		<id id="Class3"/>
		<id id="Class6"/>
		<class>
			<id.ref type="::">
				<id.ref id="Class1"/>
				<id.ref id="Class2" type="&lt;&gt;">
					<id.ref id="Class3"/>
					<id.ref id="Class4" type="&lt;&gt;"/>
				</id.ref>
				<id.ref id="Class5"/>
			</id.ref>

			<access access="protected">
				<id.ref id="Class6"/>
			</access>

			<access access="protected">
				<template>
					<id id="Class100"/>
					<class>
						<id.ref id="Class10"/>
					</class>
				</template>
			</access>

			<access access="private">

				<method id="Function">
					<id.ref id="void"/>
				</method>

				<method id="Function">
					<virtual/>
					<id.ref id="Class5" type="&lt;&gt;">
						<id.ref id="void"/>
					</id.ref>
					<parameter><id.ref id="int"/></parameter>
				</method>

				<method id="Function">
					<virtual/>
					<id.ref id="void"/>
					<parameter><id.ref id="int"/></parameter>
					<parameter><id.ref id="Class3"/></parameter>
					<const/>
					<abstract/>
				</method>
			</access>

		</class>
	</template>

	<template>
		<id id="Class100"/>
		<class>
			<id.ref id="Class10"/>
		</class>
	</template>

	<template>
		<class>
			<id.ref id="Class11"/>

			<access access="public">

				<id.ref id="Class16"/>

				<id.ref id="Class17" type="&lt;&gt;">
					<id.ref type="::">
						<id.ref id="Class23"/>
						<id.ref id="Class24"/>
						<id.ref id="Class25"/>
					</id.ref>
					<id.ref id="Class18" type="&lt;&gt;">
						<id.ref id="Class19"/>
					</id.ref>
				</id.ref>

				<class>
					<id.ref id="Class10"/>

				</class>
			</access>

		</class>
	</template>

</namespace>
</namespace>
</namespace>

</header>

<code>

<namespace id="cbear_berlios_de">
<namespace id="cpp">
<namespace id="examples">
</namespace>
</namespace>
</namespace>

</code>

</unit>
