=== BackupTheBerlios/cbear-svn/trunk/cbear.sourceforge.net/cpp/main.xsd
<?xml version="1.0"?>
<schema 
	xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://cbear.sourceforge.net/cpp"
	xmlns:cpp="http://cbear.sourceforge.net/cpp"
	elementFormDefault="qualified"
	attributeFormDefault="unqualified">

	<!-- 
		A unit contains a header file (.hpp) and a code file (.cpp).	
		A unit has a name.
	-->
	<element name="unit">
		<complexType>
			<sequence>
				<element ref="cpp:header"/>
				<element ref="cpp:code" minOccurs="0"/>
			</sequence>
			<attribute name="id" type="cpp:id"/>
		</complexType>
	</element>

	<element name="header" type="cpp:content"/>
	<element name="code" type="cpp:content"/>

	<!-- A content contains namespaces, templates and classes. -->
	<complexType name="content">
		<sequence>
			<element ref="cpp:include" minOccurs="0" maxOccurs="unbounded"/>
			<choice minOccurs="0" maxOccurs="unbounded">
				<element ref="cpp:namespace"/>
				<element ref="cpp:template"/>
				<element ref="cpp:class"/>
			</choice>
		</sequence>
	</complexType>

	<!-- An include. -->
	<element name="include">
		<complexType>
			<attribute name="href" type="cpp:href"/>
		</complexType>
	</element>

	<!-- href. -->
	<simpleType name="href">
		<restriction base="string"/>
	</simpleType>

	<!-- 
		A namespace contains everything a content has. 
		A namespace has a name.

			namespace Example
			{
				...
			}
	-->
	<element name="namespace">
		<complexType>
			<choice minOccurs="0" maxOccurs="unbounded">
				<element ref="cpp:namespace"/>
				<element ref="cpp:template"/>
				<element ref="cpp:class"/>
			</choice>
			<attribute name="id" type="cpp:id"/>
		</complexType>
	</element>

	<!--
		A template contains parameters and a class.

			template<class Id1, class Id2>
			class Id
			{
				...
			};
	-->
	<element name="template">
		<complexType>
			<sequence>
				<element ref="cpp:id" minOccurs="0" maxOccurs="unbounded"/>
				<element ref="cpp:class"/>
			</sequence>
		</complexType>
	</element>

	<!--
		A class has a type name, references on parent types and methods.
	
			class Name1::Name2<Name3, Name4<Name5::Name6 > >::Name7: public Parent1
			{
				...
			};
	-->
	<element name="class">
		<complexType>
			<sequence>
				<element ref="cpp:type.ref"/>
				<element ref="cpp:access" minOccurs="0" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>

	<!-- An access. public/private/protected. -->
	<element name="access">
		<complexType>
			<choice minOccurs="0" maxOccurs="unbounded">
				<element ref="cpp:type.ref"/>
				<element ref="cpp:method"/>
				<element ref="cpp:class"/>
				<element ref="cpp:template"/>
			</choice>		
			<attribute name="access" type="cpp:access"/>
		</complexType>	
	</element>

	<!-- An access: public, private or protected. -->
	<simpleType name="access">
		<restriction base="string">
			<enumeration value="public"/>
			<enumeration value="private"/>
			<enumeration value="protected"/>
		</restriction>
	</simpleType>

	<!-- A method 

				virtual Name1::Name2 Method(Name1, Name2<Name3>::Name4) const = 0;
	-->
	<element name="method">
		<complexType>
			<sequence>
				<element ref="cpp:virtual" minOccurs="0"/>
				<element ref="cpp:type.ref"/>
				<element ref="cpp:parameter" minOccurs="0" maxOccurs="unbounded"/>
				<element ref="cpp:const" minOccurs="0"/>
				<element ref="cpp:abstract" minOccurs="0"/>
			</sequence>
			<attribute name="id" type="cpp:id"/>
		</complexType>
	</element>

	<!-- A virtual option. -->
	<element name="virtual"/>

	<!-- A virtual option. -->
	<element name="abstract"/>

	<!-- A method parameter -->
	<element name="parameter">
		<complexType>
			<sequence>
				<element ref="cpp:type.ref"/>
			</sequence>
			<attribute name="id" type="cpp:id" use="optional"/>
		</complexType>
	</element>

	<!--
		A type reference is a sequence (path) of type names.

			Name1::Name2::Name3::Name4
	-->
	<element name="type.ref">
		<complexType>
			<sequence>
				<element ref="cpp:type.id" maxOccurs="unbounded"/>				
			</sequence>
		</complexType>
	</element>

	<!--
		A type name contains a name and optional type parameters.

			Name1<Name2, Name3, Name4>
	-->
	<element name="type.id">
		<complexType>
			<sequence>
				<element ref="cpp:type.parameters" minOccurs="0"/>
			</sequence>
			<attribute name="id" type="cpp:id"/>
		</complexType>
	</element>

	<!--
		Type parameters.

			<Name1, Name2, Name3>
	-->
	<element name="type.parameters">
		<complexType>
			<sequence>
				<element ref="cpp:type.ref" minOccurs="0" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>

	<!-- A constant. -->
	<element name="const"/>

	<!-- An id. -->
	<element name="id">
		<complexType>
			<attribute name="id" type="cpp:id"/>
		</complexType>
	</element>

	<!-- An id type. -->
	<simpleType name="id">
		<restriction base="token"/>
	</simpleType>

</schema>

=== BackupTheBerlios/cbear-svn/trunk/cbear.sourceforge.net/cpp/examples/namespace.cpp.xml
<?xml version="1.0"?>
<!--
The MIT License

Copyright (c) 2005 C Bear (http://cbear.sourceforge.net)

Permission is hereby granted, free of charge, to any person obtaining a copy of 
this software and associated documentation files (the "Software"), to deal in 
the Software without restriction, including without limitation the rights to 
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so, 
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all 
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR 
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER 
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-->
<?xml-stylesheet type="text/xsl" href="../html.xsl"?>
<unit
	xmlns="http://cbear.sourceforge.net/cpp"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://cbear.sourceforge.net/cpp ../main.xsd"
	xmlns:html="http://www.w3.org/1999/xhtml"
	id="net/sourceforge/cbear/cpp/examples/namespace">

<header>

<namespace id="net">
<namespace id="sourceforge">
<namespace id="cbear">
<namespace id="cpp">
<namespace id="examples">
</namespace>

</namespace>
</namespace>
</namespace>
</namespace>

</header>

<code>

<namespace id="net">
<namespace id="sourceforge">
<namespace id="cbear">
<namespace id="cpp">
<namespace id="examples">
</namespace>
</namespace>
</namespace>
</namespace>
</namespace>

</code>

</unit>

=== BackupTheBerlios/cbear-svn/trunk/cbear.sourceforge.net/cpp/examples/method.cpp.xml
<?xml version="1.0"?>
<!--
The MIT License

Copyright (c) 2005 C Bear (http://cbear.sourceforge.net)

Permission is hereby granted, free of charge, to any person obtaining a copy of 
this software and associated documentation files (the "Software"), to deal in 
the Software without restriction, including without limitation the rights to 
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so, 
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all 
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR 
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER 
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-->
<?xml-stylesheet type="text/xsl" href="../html.xsl"?>
<unit
	xmlns="http://cbear.sourceforge.net/cpp"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://cbear.sourceforge.net/cpp ../main.xsd"
	xmlns:html="http://www.w3.org/1999/xhtml"
	id="net/sourceforge/cbear/cpp/examples/method">

<header>

<namespace id="net">
<namespace id="sourceforge">
<namespace id="cbear">
<namespace id="cpp">
<namespace id="examples">

	<template>
		<id id="Class3"/>
		<id id="Class6"/>
		<class>
			<type.ref>
				<type.id id="Class1"/>
				<type.id id="Class2">
					<type.parameters>
						<type.ref>
							<type.id id="Class3"/>
						</type.ref>
						<type.ref>
							<type.id id="Class4">
								<type.parameters/>
							</type.id>
						</type.ref>
					</type.parameters>
				</type.id>
				<type.id id="Class5"/>
			</type.ref>

			<access access="protected">
				<type.ref>
					<type.id id="Class6"/>
				</type.ref>
			</access>

			<access access="protected">
				<template>
					<id id="Class100"/>
					<class>
						<type.ref>
							<type.id id="Class10"/>
						</type.ref>

					</class>
				</template>
			</access>

			<access access="private">

				<method id="Function">
					<type.ref><type.id id="void"/></type.ref>
				</method>

				<method id="Function">
					<virtual/>
					<type.ref>
						<type.id id="Class5">
							<type.parameters>
								<type.ref><type.id id="void"/></type.ref>
							</type.parameters>
						</type.id>
					</type.ref>
					<parameter><type.ref><type.id id="int"/></type.ref></parameter>
				</method>

				<method id="Function">
					<virtual/>
					<type.ref><type.id id="void"/></type.ref>
					<parameter><type.ref><type.id id="int"/></type.ref></parameter>
					<parameter><type.ref><type.id id="Class3"/></type.ref></parameter>
					<const/>
					<abstract/>
				</method>
			</access>

		</class>
	</template>

	<template>
		<id id="Class100"/>
		<class>
			<type.ref>
				<type.id id="Class10"/>
			</type.ref>

		</class>
	</template>

	<template>
		<class>
			<type.ref>
				<type.id id="Class11"/>
			</type.ref>

			<access access="public">

				<type.ref>
					<type.id id="Class16"/>
				</type.ref>

				<type.ref>
					<type.id id="Class17">
						<type.parameters>
							<type.ref>
								<type.id id="Class23"/>
								<type.id id="Class24"/>
								<type.id id="Class25"/>
							</type.ref>
								<type.ref>
								<type.id id="Class18">
									<type.parameters>
									<type.ref>
											<type.id id="Class19"/>
										</type.ref>
									</type.parameters>
								</type.id>
								</type.ref>
						</type.parameters>
					</type.id>
				</type.ref>

				<class>
					<type.ref>
						<type.id id="Class10"/>
					</type.ref>

				</class>
			</access>

		</class>
	</template>

</namespace>
</namespace>
</namespace>
</namespace>
</namespace>

</header>

<code>

<namespace id="net">
<namespace id="sourceforge">
<namespace id="cbear">
<namespace id="cpp">
<namespace id="examples">
</namespace>
</namespace>
</namespace>
</namespace>
</namespace>

</code>

</unit>
